### ISSUE TITLE
ui bug

### ISSUE THREAD

**Issue by bebo-dot-dev** [gameworldeos/eosgameworld#2]
I've sent EOS to your contract address and it's been eaten / lost. It looks like your UI resulted in the wrong transaction being setup in scatter which the contract can make no sense of. You have no telegram or any contact info that I can find. Pretty poor.

**Comment by gameworldeos** [comment]
we have checked, all is fine. Thanks

**Comment by bebo-dot-dev** [comment]
You're wrong, all is not fine. If everything was fine I wouldn't have raised this issue.

I've sent a direct message to the reddit u/gameworldcom account with details of the transaction. Take a look and you'll be able to see this transaction in a block explorer, my account, my attempts to withdraw and that withdraw action doing nothing at all.

Something is broken here and it needs to be fixed.

**Comment by gameworldeos** [comment]
```
Hi,

There's a bug in the UI of your game where a scatter transaction gets constructed in such a way where EOS does successfully get sent to the gameworldcom contract but it's immediately lost to the account that sent it. It doesn't show up in the "vault" and attempts to withdraw do nothing.

Thankfully the transaction that I sent was small - 1.0001 EOS as a test.

https://bloks.io/transaction/184b6262c8a9a2e452f81dded44812fcd26b7c9679dc2dd52fd858755358785c

Please send my 1 EOS back to my account: ha4dmmjqhage

This could be pretty serious for larger amounts

Cheers Joe
```
this is your message from reddit, right?

```
cleos get table gameworldcom ha4dmmjqhage player
{
  "rows": [{
      "affiliate_name": "",
      "aff_vault": 0,
      "pot_vault": 0,
      "red": 4170893,
      "blue": 0,
      "key": 4170893,
      "eos": 10001,
      "mask": 5501
    }
  ],
  "more": false
}
```
we check the table of contract and find that your key is on your account, there is no bug on contract. your cost will be listed on the right side of game screen, please check again.

**Comment by bebo-dot-dev** [comment]
Ok for some reason the game web UI has now finally updated and you're right, I can see cost and earnings on the right side and when I previously said "It doesn't show up in the vault", it now shows up there too. Not a clue what the delay was.

Please remove my personal account details and transaction from your previous above comment, I'd rather not have people being able to join the dots on my EOS account to my github account, thanks.

**Comment by gameworldeos** [comment]
@jjssoftware removed
